# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98c43b833786b2dbba1537bd9724d456480577f65eee2b4dfe4e625cc838bd8079d73462de5aecba150230835df798c57cf7c7d46de3afcfde52ec39220f440

test:
  secret_key_base: c00cd5617ab024c55903e64c79f60ea61992c6c1348cd590e732812ae2bc4fe395f3666356eb81ea7e38cb12c577d5de1a3b4ccc2f2c780d9472c6a3d114311a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
